### ISSUE TITLE
Yarn Install Broken Since 1.6.2

### ISSUE THREAD

**Issue by raray** [shubhamjain/svg-loader#36]
Error:
```
YN0009: │ external-svg-loader@npm:1.6.2 couldn't be built successfully (exit code 1, logs can be found here: /private/var/folders/06/dss6d1c143n7z9lyn1h87gkh0000gn/T/xfs-a88289a6/build.log)
```
```
# This file contains the result of Yarn building a package (external-svg-loader@npm:1.6.2)
# Script name: postinstall

No matches found: "build:*"
```
We've locked our version to `1.6.1` for now.

**Comment by raray** [comment]
I had a similar issue (https://github.com/shubhamjain/svg-loader/issues/30) that was resolved by moving the dependency from `dev` to normal dependencies. This project uses Yarn and has no such distinction

**Comment by shubhamjain** [comment]
1.6.2 is broken, but the subsequent versions are fixed. You should remove external-svg-loader and add it again. And it should work.

**Comment by raray** [comment]
@shubhamjain Hmm. I'm still getting this error:
```
external-svg-loader@npm:1.6.8 couldn't be built successfully (exit code 1 ...
```
It installs successfully after forcing it back to `1.6.1`.

**Comment by shubhamjain** [comment]
Strange. 

Doing either of
> yarn add external-svg-loader@1.6.8
> yarn add external-svg-loader

is working for me. What's the full error message? Does

> yarn remove external-svg-loader
> yarn add external-svg-loader@1.6.8

solve it?

**Comment by raray** [comment]
@shubhamjain It doesn't. I tried the above as well as blowing away my entire cache and lock file. Here's the contents of the log file:
```
# This file contains the result of Yarn building a package (external-svg-loader@npm:1.6.8)
# Script name: postinstall

No matches found: "build:*"
```
I failed to mention, and perhaps relevant, I am using `yarn@3.2.3` with PnP.

**Comment by shubhamjain** [comment]
According to https://github.com/yarnpkg/yarn/releases. The latest version 1.22.19. How are you using 3.2.3?

**Comment by raray** [comment]
> This repository holds the sources for Yarn 1.x (latest version at the time of this writing being 1.22). New releases (at this time the 3.2.3, although we're currently working on our next major) are tracked on the [yarnpkg/berry](https://github.com/yarnpkg/berry) repository, this one here being mostly kept for historical purposes and the occasional hotfix we publish to make the migration from 1.x to later releases easier.
> 
> If you hit bugs or issues with Yarn 1.x, we strongly suggest you [migrate](https://yarnpkg.com/getting-started/migration) to the latest release - at this point they have been maintained longer than 1.x, and many classes of problems have already been addressed there. By using the [nodeLinker setting](https://yarnpkg.com/configuration/yarnrc#nodeLinker) you'll also have the choice of how you want to install your packages: node_modules like npm, symlinks like pnpm, or manifest files via [Yarn PnP](https://yarnpkg.com/features/pnp).
